title: Welcome to Yuena Lin's Homepage
page-top-title: Yuena Lin
top-section-bg-text: Computer Science
home-subtitle: Yuena Lin&ensp;|&ensp;林约拿
# copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
